// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Counter struct {
	ID      int64
	Counter int64
}

type Mouse struct {
	ID            int64
	Mousedistance int64
	Leftclick     int64
	Rightclick    int64
}

type User struct {
	ID        int64
	Username  string
	Userhash  string
	Updatedat time.Time
	Createdat time.Time
}
